# Generated by Django 5.1.4 on 2024-12-18 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributors", "0002_alter_contributor_project"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                related_name="project_contributors",
                through="contributors.Contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
